---
title: CV
name: Kat
surname: Cotti
position: "Master's Student"
address: "Bren School of Environmental Science & Management"
phone: +1 805 798 4877
email: "kcotti@bren.ucsb.edu"
github: katcotti
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Kat is a first-year MESM student at the Bren School specializing in Corporate Environmental Management and Energy & Climate."
output: 
  vitae::markdowncv:
    theme: davewhipp
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```
## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bachelor of Science in Animal Science & Managerial Economics", "2019", "Davis, CA", "University of California, Davis (UCD)",
  "Master of Environmental Science and Management ", "Expected 2022", "Santa Barbara, CA", "University of California, Santa Barbara (UCSB)",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```
## Professional Experience: 

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Black Mountain Sport Horses", "1/2015 - Present", "Ojai, CA", "Assistant Trainer", 
  "La Cumbre Animal Hospital", "10/2019- 4/2020", "Santa Barbara, CA", "Veterinary Technician",
  "Karp Lab Univeristy of California Davis", "8/2018 - 6/2019", "Davis, CA",
  "Ornithology Research Assistant",
  "VIDA Volunteers", "9/2018", "Guatemala", "Veterinary Volunteer",
  "UC Davis Hunter Jumper Equestrian Team",
  "2018-2019", "Davis, CA", "President | Event's Coordinator"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
````
## Additional Experience

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "The Banff National Park Program", "2018", "Alberta, Canada", "Wildlands Studies Field Study Program",
  "UC Davis Veterinary Medicine Teaching Hospital", "9/2016 - 9/2018", "Davis, CA", "Large Animal Student Assistant",
  "Ojai Village Veterinary Hospital", "1/2014-9/2016", "Ojai, CA", "Hospital Aide"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```
## Skills & Certifications: 

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "National Geographic Pristine Seas Initiative", "Jan 2021", "Bren Group Project Proposal - Economic Implications of Protecting the Patagonia Sea", "Proposal Writing",
  "R-Studio (Website Design, Shiny Apps), Microsoft Office", " " , "Word, Excel, Powerpoint","Computer Skills:",
  "Spanish", " ", "basic conversational skills", "Language:"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```


